# Generated by Django 4.1.7 on 2023-02-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstageApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='type',
            new_name='sensor_type',
        ),
    ]
